version: '3'
services:
  nginx:  # Nginx web server
    build: prestashop-nginx:latest  # Latest Nginx Server Image
    restart: unless-stopped
    depends_on:
      - prestashop
    ports:
      - 80:80
      - 443:443
    networks:
      - prestashop_network
    volumes:
    #   - ./src:/var/www/html  # Mount the local src directory to the container
      - ./site.conf:/etc/nginx/conf.d/default.conf  # Mount the Nginx config
      # - ./ssl:/etc/nginx/ssl  # Mount the SSL folder to provide certs
      # - ng1:/templates:/etc/nginx/templates
      # - ng2:/var/www/html/  # Mount the local src directory to the container
      # - ng3:/etc/nginx/conf.d/  # Mount the Nginx config
      # - ng4:/etc/nginx/ssl/  # Mount the SSL folder to provide certs
  mysql:
    container_name: some-mysql
    image: mariadb:lts
    restart: unless-stopped
    env_file:
      - db.env
    networks:
      - prestashop_network
    volumes:
      - dbdata:/var/lib/mysql
  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:latest # Latest stable version of the PrestaShop, to see all available images go to ...
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
    env_file:
      - presta.env
    networks:
      - prestashop_network
networks:
    prestashop_network:
volumes:
  ng1:
  ng2:
  ng3:
  ng4:
  psdata:
  dbdata: