version: '4.1'
services:
  authentication:
    build: ./authentication
    ports:
      - "5000:5000"
  products:
    build: ./products
    ports:
      - "5001:5001"
  reviews:
    build: ./reviews
    ports:
      - "5002:5002"
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: prestashop
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./NGINX/nginx.conf:/etc/nginx/nginx.conf
