version: '3.8'

services:
  authentication:
    build: ./authentication
    ports:
      - "5000:5000"
    networks:
      - prestashop-network
    environment:
      - DATABASE_URL=${DATABASE_URL}

  products:
    build: ./products
    ports:
      - "5001:5001"
    networks:
      - prestashop-network
    environment:
      - DATABASE_URL=${DATABASE_URL}

  reviews:
    build: ./reviews
    ports:
      - "5002:5002"
    networks:
      - prestashop-network
    environment:
      - DATABASE_URL=${DATABASE_URL}

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: prestashop
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - prestashop-network
    volumes:
      - db-data:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./NGINX/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - prestashop-network

  prestashop-api:
    image: prestashop/prestashop:latest
    networks:
      - prestashop-network
    environment:
      - DB_SERVER=db
      - DB_NAME=prestashop
      - DB_USER=${MYSQL_USER}
      - DB_PASSWD=${MYSQL_PASSWORD}

networks:
  prestashop-network:
    driver: bridge

volumes:
  db-data:
